### PR TITLE
Use of Console for role-selector.

### LINKED ISSUE #233: [BUG] Role-Selector is just not working at all! Fix this aaagh
**Describe the bug**
When you try to add a role to the role selector console, nothing happens!

**To Reproduce**
Steps to reproduce the behavior on Discord:
1. Run the role selector command
2. try adding a role to the selector console

**Expected behavior**
The bot should ask the user what role and what emoji to add to the role selector console.

**Screenshots**

**Discord Platform**
Desktop

**Additional context**

### PR DESCRIPTION
**Pull request by JPGarCar**
# TL;DR
Since there was no real bug with role-selector, I updated the code to use the Console class.

# Description
Updated the role-selector command to use the Console class. Closes #233.

## Why
Consistency, easier to save data in the future, and we can add more explanation about the command.

## User Changes
None.

## Tests Done
Tests with and without staff role to add roles, get role and remove role. All worked!

# Breaking Changes
None.

### CODE REVIEW

File: commands/a_utility/role-selector.js [hunk 1]
```diff
@@ -50,69 +52,73 @@ class RoleSelector extends PermissionCommand {
          */
         let transfers = new Collection();
 
-        const cardEmbed = new MessageEmbed().setColor(botGuild.colors.embedColor)
-            .setTitle('Role Selector!')
-            .setDescription('React to the specified emoji to get the role, un-react to remove the role.');
+        let addTransferFeature = new Feature({
+            name: 'Add a Role!',
+            emojiName: newTransferEmoji,
+            description: 'Add a new emoji to this transfer console! Only staff can select this option!',
```
Comment (mwang2000) [inline commands/a_utility/role-selector.js:58]: @JPGarCar small thing but would it be better to print the name of the staff role instead of a hardcoded "staff" here?

Comment (JPGarCar) [reply commands/a_utility/role-selector.js:58]: Excellent idea! Will make the change.
